twig:
    file_name_pattern: '*.twig'
    date:
        format: 'd/m/Y'
    form_themes: 
        - '@TalesFromADevFlowbite/form/default.html.twig'
        - 'form/_custom_form.html.twig'
when@test:
    twig:
        strict_variables: true
